### ISSUE TITLE
nm.save on spark model has multiple sources found for parquet

### ISSUE THREAD

**Issue by Mpicca** [ing-bank/EntityMatchingModel#11]
Even adding .format at the end to specify a source do not work. Might need to be updated in the class.

![image](https://github.com/ing-bank/EntityMatchingModel/assets/24516226/aede3327-4390-42df-a954-1e03b44d0832)

**Comment by mbaak** [comment]
Hello, 
Thanks for reporting this issue, I think I see the problem. The SparkEntityMatching class does not inherit from spark's DataFrameWriter but from MLWriter, which does not support the format option (b/c normally it doesn't need it). In other words .format("...") is not picked up here. We however do store the ground-truth dataset, so the format option can be relevant - by default we set this to parquet, but atm there is no overwrite option. I will add a format function, it should be straight-forward to add.

The way it will work will become:
nm.write().format("yourformat").save(path)

Btw, looking around for this error, I'm not certain but it seems there's a spark package dependency conflict in your setup. 
See for example here:
https://stackoverflow.com/questions/63579754/error-while-read-or-write-parquet-format-data
You may want to look into this and resolve it as well. (The format function is only a workaround.)

**Comment by mbaak** [comment]
I will pick this up in the next patch release, probably in the next couple of days.

**Comment by mbaak** [comment]
Resolved with v2.1.0.
