### ISSUE TITLE
[QUESTION] Doubts about the supervised models. 

### ISSUE THREAD

**Issue by julio-correa-rios** [ing-bank/EntityMatchingModel#27]
Hi team,
I just want to start by publicly saying thanks for this incredible resource. I'm exploring it for a matching problem that I need to solve and at the moment seems very promising!

I've been running some experiments and trying to understand how the supervision work and wasn wondering whether it's possible to customise the dataset using my own, company-specific data. Looking at the function '[create_training_data()](https://github.com/ing-bank/EntityMatchingModel/blob/07dfd109af504a34274918576a6021aea46748af/emm/data/create_data.py#L455)', it looks like I can't do it. My question is:
1. Is it possible? If so, would it make any difference from this?
2. If it's not possible, is it enough with the data provided to cover all possible cases?  

Thanks a lot in advance!

All the best,
Julio

**Comment by mbaak** [comment]
Hello,
Yes, this is most certainly possible. Have a look at this tutorial notebook on how to train a new supervised model
with your own data (= list of ground truth names & list of alternative names):

https://github.com/ing-bank/EntityMatchingModel/blob/main/notebooks/03-entity-matching-training-pandas-version.ipynb

In particular this line:
p.fit_classifier(your_positive_names)
trains the classifier.

Let us know if you have any more questions.
