### ISSUE TITLE
Some questions about the package

### ISSUE THREAD

**Issue by liyifu0302** [ing-bank/EntityMatchingModel#28]
Hi team,

Firstly, I would like to express my sincere gratitude for this incredible project. I am a researcher in accounting, and I recently started a project to match company names across two research databases. This tool has truly been a lifesaver! After going through the tutorial, I have a few follow-up questions. Could you kindly take a quick look?

1. Incorporating Company and State Names in the Unsupervised Model

Currently, I am utilizing an unsupervised model based on word and n-gram cosine similarity for my US dataset. Is it possible to incorporate both company names and state names into this model? I noticed the parameter "extra_features" in your supervised model code, but I couldn't find a corresponding parameter in the unsupervised model. Any guidance on how to include these additional features would be greatly appreciated.

2. Differences Between Supervised Model Sections in Tutorials

I have found the **supervised model sections** in both of your **unsupervised and supervised** tutorials:

[01-entity-matching-pandas-version.ipynb](https://github.com/ing-bank/EntityMatchingModel/blob/main/notebooks/01-entity-matching-pandas-version.ipynb)
[03-entity-matching-training-pandas-version.ipynb](https://github.com/ing-bank/EntityMatchingModel/blob/main/notebooks/03-entity-matching-training-pandas-version.ipynb)

It seems in your first tutorial's  supervised model section, you didn't call **p.fit_classifier**. Could you please explain the differences between these two sections? Thanks!

3. In the supervised model your official website --- https://entitymatchingmodel.readthedocs.io/en/latest/parameters.html
    I found the following sentence: **input is "positive" names column 'Name' that are **_all_** supposed to match to the ground truth**
    Does that imply that I need to make sure all **train_positive_names_to_match** should be correctly matched to Ground Truth? If this is 
    the case, how could the learning be achieved (just positive, no negative matched)?

3. Behavior of supervised_on Parameter When Calling fit_classifier

After setting **supervised_on to** False, when I call the **p.fit_classifier** method, then **supervised_on** parameter is subsequently set to True. Is this  right? 

Many thanks in advance for your help!

Best,
Yifu

**Comment by liyifu0302** [comment]
For question1, could I use the following method?

In databse X, for company **ABCD** in state **California**, I just combine these two info to "**ABCD California**", then I do the same job for databse Y. Next, I try to use EMM package to match **ABCD California** in database X with **ABCD California** in database Y. Is this OK?

**Comment by mbaak** [comment]
Hello, 

Thanks for the kind words. Here are replies to your questions:
1. Matching on extra columns besides name (such as state) is not possible with out package without using a supervised model. You could do the append-trick you write about above, to make it one column. Or alternatively first match on names and then exclude all pairs where the state is different. Or train a supervised model with the extra_features included.
2. In the first tutorial a very simple supervised model is trained under the top cell with the text "Prepare very simple supervised model (only for illustration purposes)." Instructions for your own supervised model are found in the third tutorial, using p.fit_classifier(). p.fit_classifier() also calls the function train_model() after some data preparation.
3. The positive names should have a match in the ground truth, but it's not necessary for the training that these are all also correctly matched. The supervised model is trained on name-pairs, say 10 candidate name-pairs per positive name. Probably 9 out of 10 of these pairs will be incorrect, and 1 / 10 pairs is hopefully correct. So no need to provide negative names as input, you get incorrect name pairs for free.
4. Correct, after calling p.fit_classifier() the parameter supervised_on is set to True.

Hope this helps!
Best, -Max

**Comment by liyifu0302** [comment]
Thansk Max, your kind reply really helps me a lot :)

Cheers, 
Yifu
